// Copyright (c) Microsoft Corporation.  All rights reserved.
// This source code is made available under the terms of the Microsoft Public License (MS-PL)

using System;

namespace IQToolkit.Entities.Mapping
{
    /// <summary>
    /// Describes the mapping between an entity type member and a database column.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field, AllowMultiple = true)]
    public class ColumnAttribute : MemberAttribute
    {
        /// <summary>
        /// The name of the column in the database.
        /// If not specified, the name of the <see cref="MemberAttribute.Member"/> is used.
        /// </summary>
        public string? Name { get; set; }

        /// <summary>
        /// The ID of the table the column belongs to in advanced multi-table mapping.
        /// If not specified, the table ID will be the primary table's ID.
        /// </summary>
        public string? TableId { get; set; }

        /// <summary>
        /// The type of the column as describe in the database language.
        /// If not specified, the column type is inferred from the member's type.
        /// This value is used to determine the appropriate database type when sending data 
        /// during insert and update commands or to properly encode parameters.
        /// </summary>
        public string? DbType { get; set; }

        /// <summary>
        /// True if the column is computed by the database on insert/update.
        /// </summary>
        public bool IsComputed { get; set; }

        /// <summary>
        /// True if the column is part of the primary key of the table.
        /// </summary>
        public bool IsPrimaryKey { get; set; }

        /// <summary>
        /// True if the value of the column is generated by the database on insert.
        /// </summary>
        public bool IsGenerated { get; set; }

        /// <summary>
        /// True if the column is read-only. 
        /// Changes made on the client will be ignored during update.
        /// </summary>
        public bool IsReadOnly { get; set; }  
    }
}
